# Generated by Django 4.0.3 on 2022-06-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_bottles_length_bottles_neck_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flakons', to='product.category'),
        ),
    ]
