# Generated by Django 4.0.3 on 2022-06-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_bottles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottles',
            name='material',
        ),
    ]
