# Generated by Django 4.0.3 on 2022-06-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_bottles_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottles',
            name='min_order',
            field=models.IntegerField(default=100),
        ),
    ]
